import{S as a,i as c}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))t(r);new MutationObserver(r=>{for(const e of r)if(e.type==="childList")for(const n of e.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&t(n)}).observe(document,{childList:!0,subtree:!0});function i(r){const e={};return r.integrity&&(e.integrity=r.integrity),r.referrerPolicy&&(e.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?e.credentials="include":r.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function t(r){if(r.ep)return;r.ep=!0;const e=i(r);fetch(r.href,e)}})();document.querySelector(".img-list");function m(s){const o=l.imgGallery,i=s.hits.map(t=>`<li class="list-el">
                <a class="gallery-img" href="${t.largeImageURL}"><img src='${t.webformatURL}' alt='${t.tags}'></a>
                <div class="content">
                    <div class="item"><h3>Likes</h3><p>${t.likes}</p></div>
                    <div class="item"><h3>Views</h3><p>${t.views}</p></div>
                    <div class="item"><h3>Comments</h3><p>${t.comments}</p></div>
                    <div class="item"><h3>Downloads</h3><p>${t.downloads}</p></div>
                </div>
            </li>`).join("");o.innerHTML=i,new a(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function d(s){const o="https://pixabay.com",i="/api/",t=new URLSearchParams({key:"44348563-8832aea6e55efd6ddd80494f7",q:`${s}`,image_type:"photo",orientation:"horizontal",safesearch:!0}),r=`${o}${i}?${t}`;fetch(r).then(e=>{if(e.ok)return e.json();throw new Error(e.status)}).then(e=>{if(e.length===0)throw new Error("Error! Nothing to load");m(e)}).catch(e=>{c.error({title:"Sorry,",message:"there are no images matching your search query. Please try again!",color:"red"})})}const l={formEl:document.querySelector(".form-el"),inputEl:document.querySelector(".input-search"),imgGallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")};l.formEl.addEventListener("submit",s=>{s.preventDefault();const o=l.formEl.elements[0].value.trim();if(o)d(o);else{c.error({message:"Info Search input must be filled!"});return}});
//# sourceMappingURL=commonHelpers.js.map
