import{i as l}from"./assets/vendor-8e8cd629.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const i of e.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function n(t){if(t.ep)return;t.ep=!0;const e=s(t);fetch(t.href,e)}})();function a(r){const o="https://pixabay.com",s="/api/",n=new URLSearchParams({key:"44348563-8832aea6e55efd6ddd80494f7",q:`${r}`,image_type:"photo",orientation:"horizontal",safesearch:!0}),t=`${o}${s}?${n}`;return fetch(t).then(e=>e.json()).then(e=>{console.log(e),e===0&&l.show({message:"Sorry, there are no images matching your search query. Please, try again!",messageColor:"#fafafb"})}).catch(e=>{console.log(e)})}const u=document.querySelector(".img-list");let f;function m(){a().then(r=>{const o=p(r);u.insertAdjacentHTML("afterbegin",o),f.refresh()})}function d({webformatURL:r,largeImageURL:o,tags:s,likes:n,views:t,comments:e,downloads:i}){return`<li>
    <a href="${o}" class="gallery-item">
      <img src="${r}" alt="${s}" />
    </a>
    <span>likes ${n}</span>
    <span>views ${t}</span>
    <span>comments ${e}</span>
    <span>downloads ${i}</span>
    </li>`}function p(r){return Array.isArray(r)?r.map(d).join(""):(console.error("Expected an array but got:",r),"")}const c=document.querySelector(".input-search");document.querySelector(".btn-search");const h=document.querySelector(".form-el");document.getElementById("loader");h.addEventListener("submit",r=>{r.preventDefault(),c.value.trim()!==""&&(a(c.value.trim()),m())});
//# sourceMappingURL=commonHelpers.js.map
