import{S as u,i as a}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))e(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&e(l)}).observe(document,{childList:!0,subtree:!0});function s(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function e(r){if(r.ep)return;r.ep=!0;const t=s(r);fetch(r.href,t)}})();let c;document.querySelector(".img-list");function d(i){const o=n.imgGallery,s=i.hits.map(e=>`<li class="list-el">
                <a href="${e.largeImageURL}"><img src='${e.webformatURL}' alt='${e.tags}'></a>
                <div class="content">
                    <div class="item"><h3>Likes</h3><p>${e.likes}</p></div>
                    <div class="item"><h3>Views</h3><p>${e.views}</p></div>
                    <div class="item"><h3>Comments</h3><p>${e.comments}</p></div>
                    <div class="item"><h3>Downloads</h3><p>${e.downloads}</p></div>
                </div>
            </li>`).join("");o.innerHTML=s,c?c.refresh():c=new u(".gallery a",{captionsData:"alt",captionDelay:250})}function f(){n.loader.classList.remove("hidden")}function h(){n.loader.classList.add("hidden")}function m(i){const o="https://pixabay.com",s="/api/",e=new URLSearchParams({key:"44348563-8832aea6e55efd6ddd80494f7",q:`${i}`,image_type:"photo",orientation:"horizontal",safesearch:!0}),r=`${o}${s}?${e}`;return fetch(r).then(t=>{if(t.ok)return t.json();throw new Error(t.status)})}const n={formEl:document.querySelector(".form-el"),inputEl:document.querySelector(".input-search"),imgGallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")};n.formEl.addEventListener("submit",i=>{i.preventDefault();const o=n.formEl.elements[0].value.trim();if(o)m(o).then(e=>{if(e.length===0)throw new Error("Error! Nothing to load");d(e)}).catch(e=>{a.error({title:"Sorry,",message:"there are no images matching your search query. Please try again!",color:"red"})});else{a.error({message:"Info Search input must be filled!"});return}f();const s=m(o);s.length!==0&&s.then(e=>d(e.hits)),s.catch(e=>{a.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"center"})}),s.finally(()=>{h(),n.formEl.reset()})});
//# sourceMappingURL=commonHelpers.js.map
